### PR TITLE
SF30/SN30 1.29

### PR DESCRIPTION
**Pull request by guilhem**
Same rework than in #5

### CODE REVIEW

**Comment by thias** [comment]
I'm wondering about that single-cab file approach. I've had to rip out all files and references of pre-1.29 before `fwupdmgr install 8Bitdo-SF30_Pro-SN30_Pro.cab` worked, as before that it updated to 1.23, then complained that 1.23 was already installed (and I wanted the "latest", 1.29).

Thanks a lot nevertheless, I've updated my SN30 Pro from Fedora!

**Comment by brianredbeard** [comment]
@thias this is actually somewhere between an ordering issue and a bug in `fwupdmgr` parsing cab files.  I tried out simply moving the definition of 1.29 to the top of the list in the `<releases>` section and it was parsed correctly.

```
$ fwupdmgr install 8Bitdo-SF30_Pro-SN30_Pro.cab 
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Installing on 8Bitdo  …  [     \                                 ]
Restarting device…       [***************************************]failed to get device after update: failed to wait for detach replug: device 0703a244275ed772f8e276c4b31389afc296101d did not come back
```

_At this point it was booting into "wiimote" / "switch" mode, so I had to switch it to "d-input"._

```
$ fwupdmgr
...
8Bitdo SN30 Pro
  DeviceId:             0703a244275ed772f8e276c4b31389afc296101d
  Guid:                 1bf5ac96-99ce-54f2-abf4-7eabe6802533
  Guid:                 81becceb-f87b-5c66-b30a-b0958043d65d
  Guid:                 5bc60e62-f461-58bd-91b6-7de3392f8bd6
  Guid:                 afa5518d-7c55-51cb-8e1c-bf3b11b67dfa
  Guid:                 cee9c5bc-aa12-51eb-a220-d0ef588d7cb2
  Guid:                 571229d5-caed-5cbc-91c1-5c216601a194
  Guid:                 043c7673-bd45-5e2e-b8b9-c22df2dfec2a
  Guid:                 b02f1319-c1c4-54f4-b7f2-5bb3552f6a9e
  Summary:              A redesigned classic game controller
  Plugin:               ebitdo
  Flags:                updatable|supported|needs-bootloader|registered
  Vendor:               8Bitdo
  VendorId:             USB:0x2DC8
  Version:              1.29
  Icon:                 input-gaming
  InstallDuration:      120
  Created:              2019-01-22
```

**Comment by brianredbeard** [comment]
weeeellllllll.... @hughsie already did the work for us.

[facepalm](https://media.giphy.com/media/iGNiqAuwG9dwQ/giphy-downsized.gif)

```
$ make check
appstream-util validate-relax sf30sn30pro.metainfo.xml
sf30sn30pro.metainfo.xml: FAILED:
• tag-invalid           : <release> versions are not in order [1.23 before 1.25]
• tag-invalid           : <release> versions are not in order [1.25 before 1.26]
• tag-invalid           : <release> versions are not in order [1.26 before 1.29]
Validation of files failed
make: *** [Makefile:15: check] Error 1
```

**Comment by guilhem** [comment]
As said in #5 this is only a test (to have a single cab for all releases).
And hughsie prefer 1 single cab per release.

I already have done this rework for N30 Pro 2, and have to do the same here. It's only a matter of time.

**Comment by guilhem** [comment]
You can test it.

**Pull request merged**
