### PR TITLE
[WIP] Add support for 8bitdo USB Retro Receiver

### PR DESCRIPTION
**Pull request by sigboe**
Add support for 8bitdo USB Retro Receiver

I have tested this locally and it updates and it works. It is a work in progress because am waiting to receive the "8bitdo USB Retro Receiver for PS" which should arrive within a few days. I just want to make sure they are compatible and don't over-write each others firmware. 

There is an accompanying pull request here https://github.com/hughsie/fwupd/pull/1224

### CODE REVIEW

**Comment by hughsie** [comment]
Looks good, please yell when you'd like me to merge this.

**Comment by sigboe** [comment]
@hughsie I received the "8bitdo USB Wireless Receiver for PS" and while in DFU mode it identifies as the same device.

They have a bit different firmware, it might be possible to flash them with each others firmware. AFAIK the only difference between the firmwares are what mode they default to.

Is it possible to give ebitdo plugin the ability to see which of them is connected, even though they have the same PID and VID?

**Comment by hughsie** [comment]
> Is it possible to give ebitdo plugin the ability to see which of them is connected

How would it tell them apart?

**Comment by sigboe** [comment]
@hughsie 

Good news! I tried to flash the firmware for the "8bitdo USB Wireless Receiver" to the "8bitdo USB Wireless Receiver for PS" and it wrote successfully. Even better news is that it still retained the identity as "for PS" when I plugged it out and in again. And it successfully updated.

I hypothesise that there is an area of the memory where the program is stored, and also an area where settings are stored which are not overwritten when updating. E.G. since the PS3 controllers require the bluetooth host to remember the MAC and not the other way around. And that area is where the setting for if this should default to starting in Xinput (works on the switch) or Dinput (works on the PS).

So I think its safe to merge this!

**Comment by hughsie** [comment]
> So I think its safe to merge this!

Good news indeed, thanks for the great testing. I'll merge and get a package up on the LVFS now.

**Pull request merged**
